### ISSUE TITLE
Default params not working

### ISSUE THREAD

**Issue by macimovic** [jmmanley/conv-autoencoder#2]
Hi there, I tried creating an instance of the class ConvAutoEncoder with the default parameters and the execution failed.

**Comment by jmmanley** [comment]
Thanks @macimovic! Turns out there was a reshaping bug in the decoder section - addressed in the latest commit. Note that in general I wasn't super careful about how arbitrary filter sizes, etc. will work here, but happy to help with any other issues you run into.
