### ISSUE TITLE
how to change the below code with own data set 

### ISSUE THREAD

**Issue by PadminiMansingh** [jmmanley/conv-autoencoder#3]
# load MNIST dataset
import urllib, gzip, pickle

mnistfile = 'mnist.pkl.gz'
if not os.path.isfile(mnistfile):
    url = urllib.request.URLopener()
    url.retrieve("http://deeplearning.net/data/mnist/mnist.pkl.gz", mnistfile)
f = gzip.open(mnistfile, 'rb')

training_set, validation_set, testing_set = pickle.load(f, encoding='latin1')

f.close()

X_train,    y_train    = training_set
X_validate, y_validate = validation_set
X_test,     y_test     = testing_set

**Comment by jmmanley** [comment]
Hi @PadminiMansingh 

The code you copied there is from my test notebook where I load MNIST as an example dataset. You can ignore that and load your own images into a matrix `X_train`, which is size `(N,m,p)`, where `N` is the number of images in the training set, and each image is `m` by `p` pixels.

If you have a more specific question, please ask.

**Comment by jmmanley** [comment]
@PadminiMansingh I will close this issue for now, but please let me know if you have any issues with code.
